#!/bin/bash

notify-sentinela "Clonando repositório"

cd /lab
git clone $1

notify-sentinela "Iniciando processo de instalação"

cd $1

yarn

notify-sentinela "Instalação concluida, execute manualmente a inicialização"
