#!/usr/bin/env python

import sys
import os
import subprocess
import pprint
env = os.environ
keys = filter( lambda k: k.startswith('SHELLAC_'), env.keys() )
keys.sort()
output = ""   
for k in keys:
    output += k + ":" + env[k] + "\n"

subprocess.Popen(['notify-send', 'Dump', output])

