#!/bin/bash


command='DISPLAY=:0 nohup chromium --maximized --no-sandbox --incognito --disable-web-security --test-type --disable-warnings --user-data-dir=/tmp '
sudo ssh root@10.0.1.1 "$command $1" & disown

